### ISSUE TITLE
straight.el recipe

### ISSUE THREAD

**Issue by progfolio** [akirakyle/emacs-webkit#1]
This should be enough to get started (assuming the user is on the "develop" branch of straight.el):

```emacs-lisp
(straight-use-package
 '(webkit :type git :host github :repo "akirakyle/emacs-webkit"
          :branch "main"
          :files (:defaults "*.js" "*.css")
          :build ("make")))
```

**Comment by akirakyle** [comment]
Wow this is great! I've been waiting for straight to add custom build commands for awhile now. I'll go ahead and add this to the readme.
