### ISSUE TITLE
webkit-module needs to be compiled 

### ISSUE THREAD

**Issue by matteha** [akirakyle/emacs-webkit#11]
Fantastic package! I am using DOOM emacs 28 native comp, and using the straight recipe mentioned:

```
(straight-use-package
 '(webkit :type git :host github :repo "akirakyle/emacs-webkit"
          :branch "main"
          :files (:defaults "*.js" "*.css")
          :build ("make")))
```

and tried below as well:

```
(straight-use-package
 '(webkit :type git :host github :repo "akirakyle/emacs-webkit"
          :branch "main"
          :no-byte-compile t
          :files (:defaults "*.js" "*.css")
          :build ("make")))
```

but it keeps giving me the error:

if: webkit needs ‘webkit-module’ to be compiled!

Although I do have the webkit-module.so compiled by straight:

```
➜  emacs-webkit git:(main) ✗ pwd
/home/linux/.emacs.d/.local/straight/repos/emacs-webkit
➜  emacs-webkit git:(main) ✗ ls -latrah webkit-module.so
-rwxrwxr-x. 1 linux linux 49K Nov 22 22:52 webkit-module.so
➜  emacs-webkit git:(main) ✗ 
```

**Comment by bqv** [comment]
I'm willing to bet its just not being put in the right place. Fiddle `webkit-base-dir`?

**Comment by matteha** [comment]
webkit--base is a variable without a source file.

Value
"/home/linux/.emacs.d/.local/straight/repos/emacs-webkit/"

**Comment by akirakyle** [comment]
Can you try loading it directly with `(module-load "/path/to/module.so")`?

**Comment by MagicRB** [comment]
Adding `"*.h" "*.c" "Makefile"` to the `:files` section fixed it for me, straight only includes `.js` and `.css` files as instructed, which prevents the module from building

**Comment by akirakyle** [comment]
Ah I haven't had the chance to test the straight recipe myself so sorry for the omission. I'll update the readme

**Comment by MagicRB** [comment]
Happy to help, this seems to me as a really cool project!
