### ISSUE TITLE
Transfer webkit view between frames

### ISSUE THREAD

**Issue by bqv** [akirakyle/emacs-webkit#16]
Just asking the question. I would assume this works within the same emacsclient process, but not otherwise. Am I correct?

**Comment by akirakyle** [comment]
Yeah I've tried to make sure that switching to a webkit buffer in another frame than the one it is currently tied to seamlessly moves it to the new frame. It should work fine moving the webkit view between different frames started from different emacsclient processes, but I can't recall if I've tested that specifically and I'm sure there are edge cases I'm not accounting for.

**Comment by bqv** [comment]
Fantastic. I'll test this shortly, but that's a killer feature

**Comment by bqv** [comment]
Oh yeah, this worked
