### ISSUE TITLE
error: void-function webkit--format-state

### ISSUE THREAD

**Issue by yqu212** [akirakyle/emacs-webkit#17]
I get the following error after updating emacs-webkit from 781ec593 to 26a2c74c. 26a2c74c introduced webkit--format-state without defining it.

> Error during redisplay: (eval (webkit--format-state)) signaled (void-function webkit--format-state) [2 times]

**Comment by akirakyle** [comment]
Oops, I should've tested that commit before merging it. Anyways its fixed now with the latest commit.
