### ISSUE TITLE
Failed to get the memory usage

### ISSUE THREAD

**Issue by yqu212** [akirakyle/emacs-webkit#21]
When I start emacs GUI from terminal and open webkit, I get the above message from terminal.

Moreover, I encounter a maybe related issue: some page is loaded very slowly.

**Comment by akirakyle** [comment]
WebKit has a mechanism that watches memory usage and tries to free stuff when under memory pressure. I guess it's letting you know it can't detect the memory usage on your system. WebKitGTK doesn't seem to expose any interface to control this and it's unfortunate it outputs to stdout as it messes up TUI emacs.

**Comment by yqu212** [comment]
I see. As long as Emacs doesn't crash, I don't mind seeing this message.

I guess this issue is related to wsl 1. Then I close this issue now. If I find new information, I will reopen it.

**Comment by yqu212** [comment]
This issue is also observed on Midori.
