### ISSUE TITLE
Slow loading

### ISSUE THREAD

**Issue by yqu212** [akirakyle/emacs-webkit#22]
The first url can load normally.  If I use a new session, the other url will take more than one minute to load.

**Comment by yqu212** [comment]
It's not related to Emacs GUI. I can use Emacs normally when the webkit is loading.

**Comment by akirakyle** [comment]
Do you also encounter this issue on other webktigtk based browsers like Epiphany?

**Comment by yqu212** [comment]
I'll try it.

Another guy encountered the same issue. https://emacs-china.org/t/emacs-webkit-xwidget-webkit/15277/19

**Comment by yqu212** [comment]
I have tried ehiphany. It can not start on wsl 1.

> $ epiphany
> Gtk-Message: 09:32:55.623: Failed to load module "colorreload-gtk-module"
> 
> ** (epiphany:3424): WARNING **: 09:32:56.567: Error loading plugin: libaspell.so.15: cannot open shared object file: No su
> ch file or directory
> 
> 
> ** (epiphany:3424): WARNING **: 09:32:56.580: Error loading plugin: libhspell.so.0: cannot open shared object file: No suc
> h file or directory
> 

> ** (epiphany:3424): WARNING **: 09:32:56.621: Error loading plugin: libnuspell.so.4: cannot open shared object file: No su
> ch file or directory


> ** (epiphany:3424): WARNING **: 09:32:56.635: Error loading plugin: libvoikko.so.1: cannot open shared object file: No suc
> h file or directory
> 
> 
> ** (epiphany:3424): WARNING **: 09:32:57.212: memfd_create failed: Function not implemented
> 
> ** (epiphany:3424): WARNING **: 09:32:57.216: memfd_create failed: Function not implemented
> 
> ** (epiphany:3424): ERROR **: 09:32:57.217: Failed to write memfd
> [1]    3424 trace trap (core dumped)  epiphany

**Comment by yqu212** [comment]
I also tried Midori. I encountered the same issue as webkit. New tab loads url very slow.

> (midori:3604): GLib-GObject-WARNING **: 09:53:25.170: ../glib/gobject/gbinding.c:271: Unable to convert a value of type gpointer to a value of type CairoSurface
> Failed to get the memory usage

However, when I  turn on  **Privacy Browsing**, loading time become much less.

> Loading  baidu.com needs more than 4mins **without** Privacy Browsing.
> Loading  baidu.com needs about 12s **with** Privacy Browsing.

> Loading  github.com needs more than 4mins **without** Privacy Browsing.
> Loading  github.com needs about 47s **with** Privacy Browsing.

Midori's Privacy Browsing

> Midori doesn't store any personal data:
>     No history or web cookies are being saved.
>     HTML5 storage, local database and application caches are disabled.
> Midori prevents websites from tracking the user:
>     DNS prefetching is disabled.

**Comment by yqu212** [comment]
I have confirmed that WebKit runs normally on wsl 2. This issue is related to wsl 1. Maybe switching to wsl 2 is a good idea.

**Comment by akirakyle** [comment]
I've never used wsl so I can't really comment on this issue further. From what I understand wsl 1 suffers many performance issues in translating linux syscalls, so it's likely inherent to that approach, which wsl 2's virtualization does not suffer.

**Comment by yqu212** [comment]
I agree with you. Wsl 2 is the right way to use WebKit.
