### ISSUE TITLE
Incorrect font

### ISSUE THREAD

**Issue by yqu212** [akirakyle/emacs-webkit#25]
webkit
![image](https://user-images.githubusercontent.com/5894444/103058761-1b6b3880-45de-11eb-8783-f52256d4aac5.png)
microsoft edge
![image](https://user-images.githubusercontent.com/5894444/103058784-2d4cdb80-45de-11eb-928e-7a0d4092b7d9.png)

**Comment by akirakyle** [comment]
I suspect this is also a webkit, not an emacs issue since webkit is handling fonts itself independent of emacs. Test on another webkit based browser such as epiphany to confirm.

**Comment by yqu212** [comment]
I think so, too. I will confirm it in midori.

**Comment by yqu212** [comment]
I have confirmed that midori has the same issue.

**Comment by bqv** [comment]
@yqu212 you should close this issue then. It's a webkit issue, not an emacs-webkit one

**Comment by yqu212** [comment]
Sorry.
