### ISSUE TITLE
Eshell not working after loading webkit?

### ISSUE THREAD

**Issue by GorrillaRibs** [akirakyle/emacs-webkit#37]
I'm not too sure how to debug this as it seems super odd, but it seems like if I open an eshell buffer after I open a webkit buffer (or have an eshell open beforehand) whatever external (i.e. not elisp) command I run in eshell hangs (easy to produce with uname). Is this a known issue, and how I go about fixing this? I'm running on the pgtk branch on linux w/ wayland, if that might make a difference. Thanks in advance!

**Comment by akirakyle** [comment]
I suspect this is due to something being broken with the signal handling between emacs and webkitgtk processes. This is a subtle issue that I haven't had the time to dive into again, but is my first priority to fix when I have the chance.
