### ISSUE TITLE
tls/ssl

### ISSUE THREAD

**Issue by mikereape** [akirakyle/emacs-webkit#41]
Hi so I've managed to build emacs in Ubuntu 21.10 with gccemacs and pgtk and your emacs-webkit. Everything goes swimmingly except for one thing: namely, that every time I need to switch from http to https emacs complains about tls/ssl support being unavailable and that I need to install glib-networking. Thing is glib-networking and gnutls are installed as well as git with all its usual ssl stuff included. I'll spare you the install log unless you ask for it. I know that emacs-webkit acts like an honest to goodness browser and so it has to have tls/ssl support just like any browser but AFAICT that should all be covered. I'm sure this is off-topic for you but I could really use some advice, even just an off the cuff zero thought five second to write suggestion cause this is kinda out of my comfort zone. So to speak. Even if you could just tell me how to check if emacs in general has tls/ssl support installed and working that would be really helpful in terms of process of elimination. I wouldl be extremely grateful for anything you can suggest. FWIW BTW anything that doesn't require https seems to work like a champ. For example, the Bibi epub viewer works just fine.Very cool. Very cool indeed. BTW again FWIW, I built this in docker to eliminate any issues with my dev env. Best, Mike

**Comment by akirakyle** [comment]
Sorry for not responding until now. See my recent update to the README about this project going forward.
