### ISSUE TITLE
setq: peculiar error

### ISSUE THREAD

**Issue by bqv** [akirakyle/emacs-webkit#8]
Output to `*Messages*` on calling `webkit`. No further error.

**Comment by akirakyle** [comment]
Do you happen to use `tool-bar-mode` or `menu-bar-mode`? I just encountered this error when enabling them and it looks like the module is throwing a lisp error but for some reason `peculiar error` is all that shows up.

**Comment by bqv** [comment]
Yep, menu-bar is on, no toolbar though

**Comment by bqv** [comment]
Can no longer reproduce, and technically duplicate anyway
